Repository WildCodeSchool/lyon-js-sept-2020-g3, pull requests merged in 2020-11, with the labels that each got.

#37 Question
  README.md
  src/Images/etoile.jpg
  src/components/Question.js
  src/components/Question.scss
Labels: Changes requested

#39 feature added which allows to send the question by pressing enter key
  package-lock.json
  package.json
  src/components/Question.js
  src/components/Question.scss
Labels: Ready for prod

#40 Question hook refactoring
  src/components/Question.js
Labels: Ready for prod

#41 css for bubble and button, responsiv too
  src/Images/etoile.jpg
  src/Images/robot.gif
  src/components/Question.js
  src/components/Question.scss
Labels: Ready for prod

#44 Question conversation board
  src/App.js
  src/components/Question.js
  src/components/Question.scss
Labels: Ready for prod

#43 Play
  package-lock.json
  src/App.js
  src/components/Akinator.js
  src/components/Home.js
  src/components/Navbar.js
  src/components/Play.js
  src/components/StartButton.js
  src/components/inputGame.js
Labels: Changes requested

#52 Store
  .env
  package-lock.json
  src/App.js
  src/components/Akinator.js
  src/components/Akinator.scss
  src/components/Item.js
  src/components/ItemDetails.js
  src/components/Navbar.js
  src/components/Question.scss
  src/components/Store.js
  src/components/store.scss
  src/pictures/drunkBot.jpg
  src/pictures/matthieu.png
  src/pictures/pierre.png
  src/pictures/thomas.png
  src/pictures/yoda.png
Labels: Ready for prod

#53 contact files js and scss
  package-lock.json
  package.json
  src/Images/Archibot.gif
  src/Images/BurgerMenu.png
  src/Images/screen@4x.png
  src/components/Contact.js
  src/components/Contact.scss
  src/components/Form.js
  src/components/StarRated.js
  src/components/StarRating.css
  src/components/StarRating.js
Labels: Ready for prod

#51 Question conversation
  package-lock.json
  package.json
  src/Images/robot.gif
  src/components/Home.js
  src/components/Home.scss
  src/components/Question.js
  src/components/Question.scss
Labels: Ready for prod

#64 Play
  .vscode/launch.json
  package-lock.json
  src/components/Akinator.js
  src/components/Akinator.scss
  src/components/Play.js
Labels: Ready for prod

#65 Contact responsive & background composant with animated stars
  src/Images/star3.png
  src/components/Akinator.js
  src/components/Akinator.scss
  src/components/Background.js
  src/components/Background.scss
  src/components/Contact.js
  src/components/Contact.scss
  src/components/Form.js
  src/components/Question.scss
  src/components/Settings.js
  src/components/Settings.scss
  src/components/StarRating.js
Labels: Ready for prod

#67 Amandine home
  package-lock.json
  src/App.js
  src/components/Background.js
  src/components/Background.scss
  src/components/Home.js
  src/components/Home.scss
  src/components/Navbar.js
  src/components/Navbar.scss
Labels: Ready for prod

#63 responsive CSS for question page and navbar height modification
  package-lock.json
  package.json
  src/Images/conversation.png
  src/components/Background.js
  src/components/Navbar.js
  src/components/Question.js
  src/components/Question.scss
Labels: Ready for prod

#68 Contact
  src/Images/star3.png
  src/components/Akinator.js
  src/components/Akinator.scss
  src/components/Background.scss
  src/components/Contact.js
  src/components/Contact.scss
  src/components/Form.js
  src/components/Settings.js
  src/components/Settings.scss
  src/components/StarRating.js
Labels: Ready for prod

#70 Play part done with responsive
  package-lock.json
  package.json
  src/Images/workInProgress.png
  src/components/Akinator.js
  src/components/Akinator.scss
  src/components/Connexion.js
  src/components/Connexion.scss
  src/components/ItemDetails.js
  src/components/Modal.js
  src/components/Modal.scss
  src/components/Store.js
  src/components/store.scss
  src/pictures/110660_320.png
  src/pictures/votedry1.gif
Labels: Ready for prod

#66 Connexion
  package-lock.json
  package.json
  src/Images/workInProgress.png
  src/components/Connexion.js
  src/components/Connexion.scss
  src/components/ItemDetails.js
  src/components/Modal.js
  src/components/Modal.scss
  src/components/Settings.js
  src/components/Store.js
  src/components/store.scss
Labels: Ready for validation

#73 Progress bar done with responsive and connexion to the back button
  src/components/Akinator.js
  src/components/Akinator.scss
Labels: Ready for validation

#72 Sprint 4 question css
  src/App.js
  src/Images/ReactionArchiGIF/archibot-amoureux.gif
  src/Images/ReactionArchiGIF/archibot-bouche-classique.gif
  src/Images/ReactionArchiGIF/archibot-clin-doeil.gif
  src/Images/ReactionArchiGIF/archibot-dingo.gif
  src/Images/ReactionArchiGIF/archibot-grosse-bouche.gif
  src/Images/ReactionArchiGIF/archibot-incompris.gif
  src/Images/ReactionArchiGIF/archibot-mecontent.gif
  src/Images/ReactionArchiGIF/archibot-sad.gif
  src/Images/beer.png
  src/components/Navbar.js
  src/components/Question.js
  src/components/Question.scss
  src/components/QuestionDrunk.js
  src/components/QuestionDrunk.scss
Labels: Ready for prod

#69 Store 'mobile' view done
  package-lock.json
  package.json
  src/components/Akinator.js
  src/components/Connexion.js
  src/components/Connexion.scss
  src/components/Item.js
  src/components/ItemDetails.js
  src/components/Modal.scss
  src/components/Store.js
  src/components/store.scss
Labels: Conflicts

#74 CSS finalization
  src/components/Question.js
  src/components/Question.scss
  src/components/QuestionDrunk.js
  src/components/QuestionDrunk.scss
  src/components/store.scss
Labels: Ready for prod

#75 Contact
  src/App.js
  src/components/Background.scss
  src/components/Connexion.js
  src/components/Contact.js
  src/components/Contact.scss
  src/components/Form.js
  src/components/Home.js
  src/components/Navbar.js
  src/components/Navbar.scss
  src/components/Settings.js
  src/components/Settings.scss
  src/components/SoundEffectContext.js
  src/components/audio/BackgroundSound.mp3
  src/components/audio/ButtonClick.mp3
Labels: Ready for prod

#76 Play
  src/components/Akinator.js
  src/components/Akinator.scss
  src/pictures/110660_320.png
  src/pictures/votedry1.gif
Labels: Ready for prod

#78 modal drunk bot adapted
  src/components/Item.js
  src/components/ItemDetails.js
  src/components/Modal.scss
Labels: Ready for prod

#77 Sprint 4 question css
  src/components/Question.scss
  src/components/QuestionDrunk.js
  src/components/QuestionDrunk.scss
  src/components/Settings.scss
  src/components/Store.js
  src/pictures/drunk_robot.png
  src/pictures/drunk_robot2.png
Labels: Ready for prod

#79 Final
  src/components/Akinator.js
  src/components/Akinator.scss
  src/components/Contact.scss
  src/components/Home.scss
  src/components/Item.js
  src/components/Question.js
  src/components/Question.scss
  src/components/QuestionDrunk.js
  src/components/store.scss
Labels: Ready for prod
